Add "archive leagues" feature (#97)
freeCodeCamp/league-for-good pull request #103
Opened 2018-05-14 18:46 UTC by domwakeling

Ability to archive leagues (since they can't be deleted), adding a new expandable 'Archive' entry in the `Menu` (material-ui Drawer element).

In `client/src/actions/league.js`
* add new action `switchArchiveLeague`
* add 'archived' status to existing action `editLeague` to ensure redux store stays in sync with Mongoose

In `client/src/components/dashboard/leagueTabs/leagueTabData.js`
* add data for a new 'sub-tab' in the 'settings' tab

Write new file `client/src/components/dashboard/settings/forms/LeagueArchiveForm.jsx` to provide UI in new 'sub-tab

In `client/src/components/dashboard/settings/forms/editLeageNameForm.jsx`
* add PropType validation to deal with linting errors (no change to functional code)

In `client/src/components/dashboard/settings/routes.jsx`and `client/src/components/routes.js`
* add new routes

In `client/src/components/nav/Menu.jsx` and `client/src/components/nav/MenuLeagueItem.jsx`
* refactor code for presenting leagues (which is now used twice) into separate component
* additional code to render the two lists (normal and 'archived') as appropriate
* additional code to style icons

 In `client/src/components/styles/cssDashboard.js` and `client/src/components/styles/cssMenu.js`
* additional styling rules

In `server/models/league.js`
* update schema/model to include 'archived' key

In `server/api/auth.js`
* update query method to include 'archived' value in return from Mongoose/MongoDB

In `server/api/league.js`
* update server methods to include 'archived' value

2019-05-17 17:08 UTC, paulywill requested changes
@domwakeling This is awesome!

Just testing quickly, should the confirmation checkbox read as `Check if the league should be archived`?

Rather than `team`?

![image](https://user-images.githubusercontent.com/602422/57944384-d0872c00-78a4-11e9-96b0-37a70a4b6374.png)

2019-05-17 18:51 UTC, domwakeling commented
Change made; looks as though I had also made two further minor tweaks (which have likely been superseded in the last year!) which had not been committed/pushed.

2019-05-25 13:28 UTC, paulywill approved these changes

2019-05-25 14:48 UTC, merged

2019-05-25 14:49 UTC, paulywill commented
@domwakeling ![Dwight thanks](https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif)